graph TD;
    A[Production] --> B{Product Type}
    
    B --> C[Kombucha]
    B --> D[Koji]
    B --> E[Sake]
    B --> F[Calvados]

    C --> G{Cost Management}
    D --> H{Cost Management}
    E --> I{Cost Management}
    F --> J{Cost Management}

    G --> K[Operational Costs Estimation]
    H --> L[Operational Costs Estimation]
    I --> M[Operational Costs Estimation]
    J --> N[Operational Costs Estimation]

    K --> O{Market Strategy}
    
    L --> P{Market Strategy}
    
    M --> Q{Market Strategy}
    
    N --> R{Market Strategy}

    O --> S[Target Audience Identification]
    
    P --> T[Target Audience Identification]

    Q --> U[Target Audience Identification]

    R --> V[Target Audience Identification]
